/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/646d9dcdc8a5f5bddbfac913.glb -o src/components/Avatar.jsx -r public
*/

import { useAnimations, useFBX, useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useEffect, useRef, useState } from "react";

import * as THREE from "three";

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

export function Avatar(props) {
  const scroll = useScroll();
  const { nodes, materials } = useGLTF("/models/avatarRpMe.glb");
  const { animations: idleAnimation } = useFBX(
    "/animations/StandingIdle.fbx"
  );
  const { animations: walkingAnimation } = useFBX("/animations/Walking.fbx");
  const { animations: greetingAnimation } = useFBX("/animations/TalkingPhone.fbx");

  idleAnimation[0].name = "Idle";
  walkingAnimation[0].name = "Walking";
  greetingAnimation[0].name = "Greeting";

  const [animation, setAnimation] = useState("Idle");
  
  const [visible, setVisible] =useState(true);
  const group = useRef();
  const { actions } = useAnimations(
    [idleAnimation[0], walkingAnimation[0], greetingAnimation[0]],
    group
  );
  const { script } = props;
  const {
    playAudio,

    headFollow,
    smoothMorphTarget,
    morphTargetSmoothing,
  } = {
    playAudio: false,
    headFollow: true,
    smoothMorphTarget: true,
    morphTargetSmoothing: 0.5,
  };

  // const audio = useMemo(() => new Audio(`/audios/${script.value}.wav`), [script]);
  // const jsonFile = useLoader(THREE.FileLoader, `audios/${script.value}.json`);
  // const lipsync = JSON.parse(jsonFile);

  // useFrame(() => {
  //   const currentAudioTime = audio.currentTime;
  //   if (audio.paused || audio.ended) {
  //     setAnimation("Idle");
  //     return;
  //   }

  //   Object.values(corresponding).forEach((value) => {
  //     if (!smoothMorphTarget) {
  //       nodes.Wolf3D_Head.morphTargetInfluences[
  //         nodes.Wolf3D_Head.morphTargetDictionary[value]
  //       ] = 0;
  //       nodes.Wolf3D_Teeth.morphTargetInfluences[
  //         nodes.Wolf3D_Teeth.morphTargetDictionary[value]
  //       ] = 0;
  //     } else {
  //       nodes.Wolf3D_Head.morphTargetInfluences[
  //         nodes.Wolf3D_Head.morphTargetDictionary[value]
  //       ] = THREE.MathUtils.lerp(
  //         nodes.Wolf3D_Head.morphTargetInfluences[
  //           nodes.Wolf3D_Head.morphTargetDictionary[value]
  //         ],
  //         0,
  //         morphTargetSmoothing
  //       );

  //       nodes.Wolf3D_Teeth.morphTargetInfluences[
  //         nodes.Wolf3D_Teeth.morphTargetDictionary[value]
  //       ] = THREE.MathUtils.lerp(
  //         nodes.Wolf3D_Teeth.morphTargetInfluences[
  //           nodes.Wolf3D_Teeth.morphTargetDictionary[value]
  //         ],
  //         0,
  //         morphTargetSmoothing
  //       );
  //     }
  //   });

  //   for (let i = 0; i < lipsync.mouthCues.length; i++) {
  //     const mouthCue = lipsync.mouthCues[i];
  //     if (
  //       currentAudioTime >= mouthCue.start &&
  //       currentAudioTime <= mouthCue.end
  //     ) {
  //       if (!smoothMorphTarget) {
  //         nodes.Wolf3D_Head.morphTargetInfluences[
  //           nodes.Wolf3D_Head.morphTargetDictionary[
  //             corresponding[mouthCue.value]
  //           ]
  //         ] = 1;
  //         nodes.Wolf3D_Teeth.morphTargetInfluences[
  //           nodes.Wolf3D_Teeth.morphTargetDictionary[
  //             corresponding[mouthCue.value]
  //           ]
  //         ] = 1;
  //       } else {
  //         nodes.Wolf3D_Head.morphTargetInfluences[
  //           nodes.Wolf3D_Head.morphTargetDictionary[
  //             corresponding[mouthCue.value]
  //           ]
  //         ] = THREE.MathUtils.lerp(
  //           nodes.Wolf3D_Head.morphTargetInfluences[
  //             nodes.Wolf3D_Head.morphTargetDictionary[
  //               corresponding[mouthCue.value]
  //             ]
  //           ],
  //           1,
  //           morphTargetSmoothing
  //         );
  //         nodes.Wolf3D_Teeth.morphTargetInfluences[
  //           nodes.Wolf3D_Teeth.morphTargetDictionary[
  //             corresponding[mouthCue.value]
  //           ]
  //         ] = THREE.MathUtils.lerp(
  //           nodes.Wolf3D_Teeth.morphTargetInfluences[
  //             nodes.Wolf3D_Teeth.morphTargetDictionary[
  //               corresponding[mouthCue.value]
  //             ]
  //           ],
  //           1,
  //           morphTargetSmoothing
  //         );
  //       }

  //       break;
  //     }
  //   }
  // });

  // useEffect(() => {
  //   nodes.Wolf3D_Head.morphTargetInfluences[
  //     nodes.Wolf3D_Head.morphTargetDictionary["viseme_I"]
  //   ] = 1;
  //   nodes.Wolf3D_Teeth.morphTargetInfluences[
  //     nodes.Wolf3D_Teeth.morphTargetDictionary["viseme_I"]
  //   ] = 1;
  //   if (playAudio) {
  //     audio.play();
  //     if (script === "pizzas") {
  //       setAnimation("Greeting");
  //     } else {
  //       setAnimation("Idle");
  //     }
  //   }
  //   else {
  //     setAnimation("Angry");
  //     audio.pause();
  //   }
  // }, [script]);

  // Signal that layout effects (where drei populates actions) have run
  
 
  useEffect(() => {
  if (!actions) return;

  const action = actions[animation];
  if (!action) return;

  action.reset().fadeIn(0.3).play();

  return () => action.fadeOut(0.3);
}, [animation, actions]);

const prevIsWalking = useRef(false);

useFrame(() => {
  const isWalking = scroll.offset > 0.05;
  const isEnd = scroll.offset > 0.19;
  const isContact = scroll.offset >0.8;
if (isContact) {
    setVisible(true);
    setAnimation("Greeting")
    return;
  }
  if (isEnd) {
    setVisible(false);
    return;
  }
  else {
    setVisible(true);
  }
  if (isWalking !== prevIsWalking.current) {
    prevIsWalking.current = isWalking;
    setAnimation(isWalking ? "Walking" : "Idle");
  }
  
});

useEffect(() => {
  console.log(actions);
}, [actions]);

  return visible ? (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  ): null;
}

useGLTF.preload("/models/avatarRpMe.glb");
